Added cheking]

diff --git a/scripts/dcmd b/scripts/dcmd
--- a/scripts/dcmd
+++ b/scripts/dcmd
@@ -1,6 +1,16 @@
 #!/bin/bash
-export DOCKER_ENV="$HOME/docker/environment"
-export DOCKER_PRIV_ENV="$HOME/docker-private"
+
+if [ "$DOCKER_ENV" = "" ]
+then
+  echo "CRITICAL: Environment varable DOCKER_ENV must be set to the folder containing the environnent files  used. Please resolve."
+  exit 1
+fi
+
+if [ "$DOCKER_SECRET_ENV" = "" ]
+then
+  echo "CRITICAL: Environment variable DOCKER_SECRET_ENV must be set to the folder containing the secret files used. Please resolve."
+  exit 1
+fi
 
 export DOCKER_GATEWAY_HOST=$(ip addr show dev eth0 | grep 'state UP' -A2 | tail -n1 | awk -F'[/ ]+' '{print $3}')
 export PUID="$UID"
@@ -8,11 +18,19 @@ export PGID="$UID"
 
 globalenvfile="$DOCKER_ENV/global.env"
 envfile="$DOCKER_ENV/$1.env"
-privenvfile="$DOCKER_PRIV_ENV/$1.env"
+privenvfile="$DOCKER_SECRET_ENV/$1.env"
 composefile="$HOME/docker/compose/docker-compose-$1.yml"
 stackname="$1-stack"
 cmd="$2"
 params=""
+
+if [ "$1" = "" ]
+then
+  echo "ERROR: Parameter <<stackname>> not specified"
+  echo ""
+  echo "Format: dcmd <<stackname>> <<command>>"
+  exit 1
+fi
 
 if [ ! -z "$3" ]
 then
@@ -93,10 +111,10 @@ then
         Yes) docker-compose -p $stackname -f $composefile \
                          down -v --rmi all
              echo "Deleted"
-             exit;;
+             exit 0;;
       No) echo "Aborting"
             echo ""
-            exit;;
+            exit 0;;
       esac
     done
 
@@ -109,6 +127,7 @@ then
 else
   echo Cannot find compose file: $composefile
   echo Aborting
+  exit 1
 fi
 
 echo ""
